spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: mascotas
logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5433/mascotas
#    username: postgres
#    password: sergio
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#
#  application:
server:
  port: 8080
#    name: mascotas